version: "2.0"

steps:
  - name: Build and Test
    image: node:lts
    script:
      - npm install
      - npm test

  - name: Deploy to Cloud Foundry
    image: sap/cf-cli
    script:
      - cf login -a $CF_API_ENDPOINT -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      - cf push
