version: '2.0'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build

test:
  stage: test
  image: node:16
  script:
    - npm test

deploy:
  stage: deploy
  image: node:16
  script:
    - cf login -a https://api.cf.<region>.hana.ondemand.com -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
    - npm run deploy
  environment:
    name: production
  when: manual
