version: '1.0'
steps:
  - name: build
    image: node:14
    script:
      - npm install
      - npm run build

  - name: deploy
    image: sap/cf-cli
    script:
      - cf login -a <api_endpoint> -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      - cf push
